


###

GET http://127.0.0.1:3000/

###

POST http://127.0.0.1:3000/contact-us 
Content-Type: application/json

{
    "name": "Blake Anderson",
    "email": "andersonblake@gmail.com",
    "subject": "Involvment",
    "message": "I am interested in getting more involved in the service, where do i start?"
}

###
POST http://127.0.0.1:3000/volunteer-request
Content-Type: application/json

{
    "name": "Blake Anderson",
    "email": "andersonblake@gmail.com",
    "event title": "Serve a soul",
    "date": "3/14/2023",
    "time": "1pm - 3pm",
    "location": "1234 main st. rougue, CA 91002"
}

###